id: AC3BB6634
base_file: f67E3.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:59:15.724598
  last_modified_at: 2022-05-30 22:59:15.724607
